name: CI

on:
  push:
    branches:
      - "production"
      - "staging"
    # paths:
    #   - "packages/**"

jobs:
  review-mono-repo:
    name: Review Mono Repo
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        node-version: [18.x]
        pnpm-version: [7.x]
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          cache: "pnpm"
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        env:
          CI: true

      - name: Format
        run: pnpm run format

      - name: Lint
        run: pnpm run lint

      - name: Build
        run: pnpm run build
        env:
          NODE_ENV: production
